import { FormData, Language } from './types';

export const INITIAL_FORM_DATA: FormData = {
  name: '',
  age: '',
  weight: '',
  gender: 'male',
  pregnant: 'no',
  scr: '',
  qtc: '',
  heartRate: '',
  respiratoryRate: '',
  potassium: '',
  magnesium: '',
  calcium: '',
  route: 'oral',
  dose: '500',
  myastheniaGravis: false,
  epilepsy: false,
  fluoroquinoloneAllergy: false,
  qtProlongation: false,
  heartDisease: false,
  kidneyDisease: false,
  antiarrhythmics: false,
  antipsychotics: false,
  antidepressants: false,
  macrolides: false,
  antifungals: false,
  otherQtDrugs: false,
  corticosteroids: false,
  diabetesMeds: false,
  nsaids: false,
  caffeine: false,
  alcohol: false,
};

export const TRANSLATIONS = {
  en: {
    appTitle: 'Levofloxacin Dosing Calculator',
    appSubtitle: 'Clinical decision support tool for levofloxacin dosing and safety assessment',
    step1: 'Patient Info',
    step2: 'Medical History',
    step3: 'Lab Values',
    next: 'Next',
    back: 'Back',
    calculate: 'Calculate Results',
    patientName: 'Patient Name',
    enterName: 'Enter name',
    age: 'Age (years)',
    weight: 'Weight (kg)',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    pregnancyStatus: 'Pregnancy Status',
    notPregnant: 'Not Pregnant',
    pregnant: 'Pregnant',
    route: 'Route',
    oral: 'Oral',
    iv: 'IV',
    dose: 'Dose (mg)',
    medicalHistory: 'Medical History',
    currentMedications: 'Current Medications',
    lifestyle: 'Lifestyle Factors',
    myastheniaGravis: 'Myasthenia Gravis',
    epilepsy: 'Epilepsy',
    allergy: 'Fluoroquinolone Allergy',
    histQt: 'History of QT Prolongation',
    heartDisease: 'Heart Disease',
    kidneyDisease: 'Kidney Disease',
    antiarrhythmics: 'Antiarrhythmics',
    antipsychotics: 'Antipsychotics',
    antidepressants: 'Antidepressants',
    macrolides: 'Macrolide Antibiotics',
    antifungals: 'Antifungals',
    otherQt: 'Other QT-prolonging Drugs',
    corticosteroids: 'Systemic Corticosteroids',
    diabetesMeds: 'Insulin/Sulfonylureas',
    nsaids: 'NSAIDs',
    caffeine: 'Regular Caffeine Use',
    alcohol: 'Regular Alcohol Use',
    scr: 'Serum Creatinine (mg/dL)',
    qtc: 'QTc Interval (ms)',
    optional: '(optional)',
    potassium: 'Potassium (mEq/L)',
    magnesium: 'Magnesium (mg/dL)',
    calcium: 'Calcium (mg/dL)',
    heartRate: 'Heart Rate (bpm)',
    respRate: 'Respiratory Rate (breaths/min)',
    contraindicationsDetected: 'CONTRAINDICATIONS DETECTED',
    assessmentComplete: 'Assessment Complete',
    patient: 'Patient',
    dosingRec: 'Dosing Recommendation',
    renalFunction: 'Renal Function',
    recRegimen: 'Recommended Regimen',
    initialDose: 'Initial Dose',
    maintenance: 'Maintenance',
    qtAssessment: 'QT Prolongation Risk Assessment',
    warnings: 'Warnings & Precautions',
    pkParams: 'Pharmacokinetic Parameters',
    adminInfo: 'Important Administration Information',
    timing: 'Timing with Food & Supplements',
    timingText: 'Take Levofloxacin 2 hours BEFORE or 6 hours AFTER:',
    sideEffects: 'Common Side Effects',
    contactDoctor: 'Contact doctor immediately if:',
    startNew: 'Start New Assessment',
    print: 'Print Results',
    disclaimer: 'For educational and clinical decision support purposes only. Always consult with a qualified healthcare provider.',
    required: 'Required',
    riskScore: 'Score',
    factorsPresent: 'Risk Factors Present',
    noteF: 'Note: Oral and IV dosing are equivalent (F ≈ 1)',
    lowRisk: 'Low Risk',
    modRisk: 'Moderate Risk',
    highRisk: 'High Risk',
    pediatricContra: 'Pediatric Contraindication',
    pregContra: 'Pregnancy Contraindication',
    hypersens: 'Hypersensitivity',
    pediatricMsg: 'Levofloxacin is contraindicated in patients under 18 years due to risk of cartilage damage.',
    pregMsg: 'Risk of fetal cartilage and bone damage - contraindicated in pregnancy.',
    mgMsg: 'Risk of severe muscle weakness and possible respiratory failure.',
    epilepsyMsg: 'Increased risk of seizures - contraindicated.',
    allergyMsg: 'Known allergy to fluoroquinolones - absolute contraindication.',
    save: 'Save Patient',
    savedSuccess: 'Patient Saved',
    history: 'Patient History',
    noHistory: 'No saved patients found.',
    load: 'Load',
    delete: 'Delete',
    date: 'Date',
    close: 'Close',
  },
  ar: {
    appTitle: 'حاسبة جرعات الليفوفلوكساسين',
    appSubtitle: 'أداة دعم القرار السريري لتحديد جرعات الليفوفلوكساسين وتقييم السلامة',
    step1: 'بيانات المريض',
    step2: 'التاريخ الطبي',
    step3: 'القيم المخبرية',
    next: 'التالي',
    back: 'سابق',
    calculate: 'حساب النتائج',
    patientName: 'اسم المريض',
    enterName: 'أدخل الاسم',
    age: 'العمر (سنة)',
    weight: 'الوزن (كجم)',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    pregnancyStatus: 'حالة الحمل',
    notPregnant: 'غير حامل',
    pregnant: 'حامل',
    route: 'طريقة الإعطاء',
    oral: 'فموي',
    iv: 'وريدي',
    dose: 'الجرعة (ملغ)',
    medicalHistory: 'التاريخ الطبي',
    currentMedications: 'الأدوية الحالية',
    lifestyle: 'عوامل نمط الحياة',
    myastheniaGravis: 'الوهن العضلي الوبيل',
    epilepsy: 'الصرع',
    allergy: 'حساسية الفلوروكينولون',
    histQt: 'تاريخ استطالة QT',
    heartDisease: 'أمراض القلب',
    kidneyDisease: 'أمراض الكلى',
    antiarrhythmics: 'مضادات اضطراب النظم',
    antipsychotics: 'مضادات الذهان',
    antidepressants: 'مضادات الاكتئاب',
    macrolides: 'المضادات الحيوية (ماكرولايد)',
    antifungals: 'مضادات الفطريات',
    otherQt: 'أدوية أخرى تطيل QT',
    corticosteroids: 'الكورتيكوستيرويدات الجهازية',
    diabetesMeds: 'الأنسولين/السلفونيل يوريا',
    nsaids: 'مضادات الالتهاب غير الستيرويدية',
    caffeine: 'تناول الكافيين بانتظام',
    alcohol: 'تناول الكحول بانتظام',
    scr: 'كرياتينين المصل (mg/dL)',
    qtc: 'فاصل QTc (ms)',
    optional: '(اختياري)',
    potassium: 'البوتاسيوم (mEq/L)',
    magnesium: 'المغنيسيوم (mg/dL)',
    calcium: 'الكالسيوم (mg/dL)',
    heartRate: 'معدل ضربات القلب (bpm)',
    respRate: 'معدل التنفس (breaths/min)',
    contraindicationsDetected: 'تم اكتشاف موانع استخدام',
    assessmentComplete: 'اكتمل التقييم',
    patient: 'المريض',
    dosingRec: 'توصيات الجرعة',
    renalFunction: 'وظائف الكلى',
    recRegimen: 'النظام العلاجي الموصى به',
    initialDose: 'الجرعة الأولية',
    maintenance: 'الجرعة المستمرة',
    qtAssessment: 'تقييم خطر استطالة QT',
    warnings: 'تحذيرات واحتياطات',
    pkParams: 'المعاملات الحركية الدوائية',
    adminInfo: 'معلومات هامة للإعطاء',
    timing: 'التوقيت مع الطعام والمكملات',
    timingText: 'تناول ليفوفلوكساسين قبل ساعتين أو بعد 6 ساعات من:',
    sideEffects: 'الآثار الجانبية الشائعة',
    contactDoctor: 'اتصل بالطبيب فوراً في حال:',
    startNew: 'بدء تقييم جديد',
    print: 'طباعة النتائج',
    disclaimer: 'للأغراض التعليمية ودعم القرار السريري فقط. استشر دائمًا مقدم رعاية صحية مؤهل.',
    required: 'مطلوب',
    riskScore: 'الدرجة',
    factorsPresent: 'عوامل الخطر الموجودة',
    noteF: 'ملاحظة: الجرعات الفموية والوريدية متكافئة (F ≈ 1)',
    lowRisk: 'خطر منخفض',
    modRisk: 'خطر متوسط',
    highRisk: 'خطر مرتفع',
    pediatricContra: 'موانع الاستخدام للأطفال',
    pregContra: 'موانع الاستخدام للحمل',
    hypersens: 'فرط الحساسية',
    pediatricMsg: 'يمنع استخدام ليفوفلوكساسين للمرضى دون سن 18 عامًا بسبب خطر تلف الغضاريف.',
    pregMsg: 'خطر تلف الغضاريف والعظام لدى الجنين - يمنع استخدامه أثناء الحمل.',
    mgMsg: 'خطر ضعف العضلات الشديد واحتمال فشل الجهاز التنفسي.',
    epilepsyMsg: 'زيادة خطر النوبات - يمنع استخدامه.',
    allergyMsg: 'حساسية معروفة للفلوروكينولونات - منع مطلق.',
    save: 'حفظ المريض',
    savedSuccess: 'تم الحفظ',
    history: 'سجل المرضى',
    noHistory: 'لا يوجد مرضى محفوظين.',
    load: 'تحميل',
    delete: 'حذف',
    date: 'التاريخ',
    close: 'إغلاق',
  }
};
